# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import Qt


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(683, 486)
        self.queueFrame = QtWidgets.QFrame(parent=Form)
        self.queueFrame.setGeometry(QtCore.QRect(360, 30, 300, 421))
        self.queueFrame.setStyleSheet("QFrame {\n"
        "    border: 1px solid black;\n"
        "    \n"
        "}\n"
        "\n"
        "QLabel {\n"
        "    border: 0;\n"
        "}")
        self.queueFrame.setObjectName("queueFrame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.queueFrame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(parent=self.queueFrame)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.queue_listWidget = QtWidgets.QListWidget(parent=self.queueFrame)
        self.queue_listWidget.setObjectName("queue_listWidget")
        self.queue_listWidget.setItemAlignment(Qt.AlignmentFlag.AlignCenter)
        self.verticalLayout_4.addWidget(self.queue_listWidget)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.enqueue_button = QtWidgets.QPushButton(parent=self.queueFrame)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        self.queue_listWidget.setFont(font)
        font.setPointSize(12)
        self.enqueue_button.setFont(font)
        self.enqueue_button.setObjectName("enqueue_button")
        self.horizontalLayout_2.addWidget(self.enqueue_button)
        self.queue_input = QtWidgets.QLineEdit(parent=self.queueFrame)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        # self.stack_listWidget.setFont(font)
        self.queue_listWidget.setFont(font)
        self.queue_input.setFont(font)
        self.queue_input.setObjectName("queue_input")
        self.horizontalLayout_2.addWidget(self.queue_input)
        self.dequeue_button = QtWidgets.QPushButton(parent=self.queueFrame)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.dequeue_button.setFont(font)
        self.dequeue_button.setObjectName("dequeue_button")
        self.horizontalLayout_2.addWidget(self.dequeue_button)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.queue_label = QtWidgets.QLabel(parent=self.queueFrame)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        self.queue_label.setFixedHeight(40)
        self.queue_label.setWordWrap(True)
        self.queue_label.setFont(font)
        self.queue_label.setObjectName("queue_label")
        self.verticalLayout_4.addWidget(self.queue_label)
        self.verticalLayout_3.addLayout(self.verticalLayout_4)
        self.stackFrame = QtWidgets.QFrame(parent=Form)
        self.stackFrame.setGeometry(QtCore.QRect(30, 30, 300, 421))
        self.stackFrame.setStyleSheet("QFrame {\n"
"    border: 1px solid black;\n"
"    \n"
"}\n"
"\n"
"QLabel {\n"
"    border: 0;\n"
"}")
        self.stackFrame.setObjectName("stackFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.stackFrame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=self.stackFrame)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.stack_listWidget = QtWidgets.QListWidget(parent=self.stackFrame)
        # self.stack_listWidget.setItemAlignment(Qt.AlignmentFlag.AlignCenter)
        self.stack_listWidget.setObjectName("stack_listWidget")
        self.verticalLayout.addWidget(self.stack_listWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.push_button = QtWidgets.QPushButton(parent=self.stackFrame)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        self.stack_listWidget.setFont(font)
        font.setPointSize(12)
        self.push_button.setFont(font)
        self.push_button.setObjectName("push_button")
        self.horizontalLayout.addWidget(self.push_button)
        self.stack_input = QtWidgets.QLineEdit(parent=self.stackFrame)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        self.stack_input.setFont(font)
        self.stack_input.setObjectName("stack_input")
        self.horizontalLayout.addWidget(self.stack_input)
        self.stack_pop = QtWidgets.QPushButton(parent=self.stackFrame)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.stack_pop.setFont(font)
        self.stack_pop.setObjectName("stack_pop")
        self.horizontalLayout.addWidget(self.stack_pop)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.stack_label = QtWidgets.QLabel(parent=self.stackFrame)
        self.stack_label.setWordWrap(True)
        self.stack_label.setFixedHeight(40)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        self.stack_label.setFont(font)
        self.stack_label.setObjectName("stack_label")
        self.verticalLayout.addWidget(self.stack_label)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "Queue (FIFO)"))
        self.enqueue_button.setText(_translate("Form", "Enqueue"))
        self.dequeue_button.setText(_translate("Form", "Dequeue"))
        self.queue_label.setText(_translate("Form", "---"))
        self.label_2.setText(_translate("Form", "Stack (LIFO)"))
        self.push_button.setText(_translate("Form", "Push"))
        self.stack_pop.setText(_translate("Form", "Pop"))
        self.stack_label.setText(_translate("Form", "---"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
